### ISSUE TITLE
Gamedata Broken for 17/11/2021 TF2 Update

### ISSUE THREAD

**Issue by punteroo** [nosoop/SM-TFEconData#13]
Update seems to have shifted the offset for ``CProtoBufScriptObjectDefinitionManager::m_PaintList``, utilized by ``Native_GetPaintKitList``.

https://github.com/nosoop/SM-TFEconData/blob/19d39d6197d4825087360f72a5adb1805d92e661/scripting/tf_econ_data.sp#L294-L296

Latest accelerator crash shows stack trace for this on Thread 0:
```
sourcepawn.jit.x86.dll!sp::ScriptedInvoker::Invoke(int *) [ scripted-invoker.cpp:301 + 0x21 ]
      https://github.com/alliedmodders/sourcepawn/blob/2239972ff621364b70828b1d14cc8bf296d06233/vm/scripted-invoker.cpp#L301
      eip: 0x6c88db99  esp: 0x008fc660  ebp: 0x008fcb44  

      008fc660  8f 00 00 00 c0 ca 8f 00  3c 71 00 00 a0 18 00 00  ........<q......
      008fc670  01 74 66 5f 65 63 6f 6e  5f 64 61 74 61 2e 73 6d  .tf_econ_data.sm
      008fc680  78 3a 3a 4e 61 74 69 76  65 5f 47 65 74 50 61 69  x::Native_GetPai
      008fc690  6e 74 4b 69 74 4c 69 73  74 00 88 6c 34 1f f6 23  ntKitList..l4..#
```
https://github.com/nosoop/SM-TFEconData/blob/19d39d6197d4825087360f72a5adb1805d92e661/scripting/tf_econ_data/paintkit_definition.sp#L7-L21
https://github.com/nosoop/SM-TFEconData/blob/19d39d6197d4825087360f72a5adb1805d92e661/scripting/tf_econ_data/paintkit_definition.sp#L40-L58

**Comment by nosoop** [comment]
Ah, this one slipped by my review; thanks for the heads-up.

It looks like `CProtoBufScriptObjectDefinitionManager::m_PaintList` should still be correct on Linux, so I'll go and check if it's a Windows thing.

**Comment by nosoop** [comment]
Nope, it's not a Windows thing &mdash; it turns out the offset of the length property for the paintkit list is bad; the null check here was papering over the actual issue where it was reading out of bounds:

https://github.com/nosoop/SM-TFEconData/blob/19d39d6197d4825087360f72a5adb1805d92e661/scripting/tf_econ_data/paintkit_definition.sp#L28-L35

Will fix shortly, but this will require a new build of the plugin since that particular offset is hardcoded.  Both Linux and Windows memory layouts are the same in this case.
