### ISSUE TITLE
Retrieving player classes which use item with specific definition index

### ISSUE THREAD

**Issue by naydef** [nosoop/SM-TFEconData#18]
I see that this plugin allows one to retrieve various info about the items.
Is it possible to implement such functionality?

Edit: I suppose using `TF2Econ_GetItemLoadoutSlot` will yield this information. If it returns `-1` then this def index is not used by this class.

**Comment by nosoop** [comment]
Correct; you'd need to iterate over the player classes and check if the result is not -1; [see the implementation in the compatibility shim](https://github.com/nosoop/SM-TFEconDataCompat/blob/b08c2b72150fcd91847afda156dc3544294dd234/scripting/tf_econ_data_compat/tf2itemsinfo.sp#L413-L425).

Since it's an abstraction over existing functionality, I don't have plans to make it its own native.
